backend:
  # name: test-repo
  name: git-gateway
  branch: main
media_folder: src/images
public_folder: /images
collections:
  - name: blog
    label: Blog
    folder: src/cms
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
